
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bankAppPack;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author Eweje Opeoluwa
 */
public class MainWin extends javax.swing.JFrame {
    private Connection con;
    private PreparedStatement ps,prs;
    private String custName;
    private int rowsAffected;
    private ResultSet rs;
    private Object ex;
  

    /**
     * Creates new form MainWin
     */
    public MainWin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameTextField1 = new javax.swing.JTextField();
        surnameTextField2 = new javax.swing.JTextField();
        sexTextField3 = new javax.swing.JTextField();
        addTextField4 = new javax.swing.JTextField();
        phonenoTextField5 = new javax.swing.JTextField();
        BalanceTextField6 = new javax.swing.JTextField();
        staffidTextField7 = new javax.swing.JTextField();
        submitButton1 = new javax.swing.JButton();
        resetButton2 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        accountNoTextField = new javax.swing.JTextField();
        amountInWordsTextField = new javax.swing.JTextField();
        withdrawalTextField = new javax.swing.JTextField();
        withdrawalButton = new javax.swing.JButton();
        clearButton1 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        acctNoTextField = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        clearButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        accNoCha = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        surname = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        backButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        accountNo2TextField = new javax.swing.JTextField();
        amtInWordsTextField = new javax.swing.JTextField();
        depositAmtTextField = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();
        clearButton3 = new javax.swing.JButton();
        backButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageFolder/sky.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel1.setText("StaffID");

        jLabel2.setText("Name");

        jLabel3.setText("Sex");

        jLabel4.setText("Surname");

        jLabel5.setText("Phone No.");

        jLabel6.setText("Address");

        jLabel8.setText("Balance");

        nameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextField1ActionPerformed(evt);
            }
        });

        surnameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextField2ActionPerformed(evt);
            }
        });

        sexTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexTextField3ActionPerformed(evt);
            }
        });

        addTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTextField4ActionPerformed(evt);
            }
        });

        phonenoTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoTextField5ActionPerformed(evt);
            }
        });

        BalanceTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceTextField6ActionPerformed(evt);
            }
        });

        staffidTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffidTextField7ActionPerformed(evt);
            }
        });

        submitButton1.setText("SUBMIT");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });

        resetButton2.setText("RESET");
        resetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton2ActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(submitButton1)
                        .addGap(64, 64, 64)
                        .addComponent(resetButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameTextField1)
                    .addComponent(surnameTextField2)
                    .addComponent(sexTextField3)
                    .addComponent(addTextField4)
                    .addComponent(phonenoTextField5)
                    .addComponent(BalanceTextField6)
                    .addComponent(staffidTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenoTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffidTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton1)
                    .addComponent(resetButton2)
                    .addComponent(backButton)))
        );

        jTabbedPane1.addTab("Register Customer", jPanel6);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Account Number");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Amount in words");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Withdrawal Amount");

        accountNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNoTextFieldActionPerformed(evt);
            }
        });

        amountInWordsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountInWordsTextFieldActionPerformed(evt);
            }
        });

        withdrawalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalTextFieldActionPerformed(evt);
            }
        });

        withdrawalButton.setText("WITHDRAWAL");
        withdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalButtonActionPerformed(evt);
            }
        });

        clearButton1.setText("CLEAR");
        clearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton1ActionPerformed(evt);
            }
        });

        backButton1.setText("BACK");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(21, 21, 21)
                        .addComponent(withdrawalTextField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountInWordsTextField)
                            .addComponent(accountNoTextField))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(clearButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(amountInWordsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(withdrawalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton1)
                    .addComponent(backButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Withdrawal", jPanel3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Account Number");

        acctNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acctNoTextFieldActionPerformed(evt);
            }
        });

        checkButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkButton.setText("CHECK");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        clearButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton2.setText("CLEAR");
        clearButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Account Number");

        accNoCha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accNoCha.setText("Account Number");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Name");

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setText("Name");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Surname");

        surname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        surname.setText("Surname");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Balance");

        balance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balance.setText("Balance");

        backButton2.setText("BACK");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(acctNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(checkButton))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(clearButton2)
                                .addGap(31, 31, 31)
                                .addComponent(backButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accNoCha)
                                    .addComponent(name)
                                    .addComponent(surname)
                                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acctNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkButton)
                    .addComponent(clearButton2)
                    .addComponent(backButton2))
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(accNoCha))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(surname, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balance)
                    .addComponent(jLabel22))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Check Account Balance", jPanel4);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Account Number");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Amount in words");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Deposit Amount");

        accountNo2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNo2TextFieldActionPerformed(evt);
            }
        });

        amtInWordsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtInWordsTextFieldActionPerformed(evt);
            }
        });

        depositAmtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositAmtTextFieldActionPerformed(evt);
            }
        });

        depositButton.setText("DEPOSIT");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        clearButton3.setText("CLEAR");
        clearButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton3ActionPerformed(evt);
            }
        });

        backButton3.setText("BACK");
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(amtInWordsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(accountNo2TextField)
                            .addComponent(depositAmtTextField)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(clearButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(backButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(accountNo2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(amtInWordsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(depositAmtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton3)
                    .addComponent(backButton3))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Deposit", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton2ActionPerformed
     nameTextField1.setText("");
     surnameTextField2.setText("");
     sexTextField3.setText("");
     addTextField4.setText("");
     phonenoTextField5.setText("");
     BalanceTextField6.setText("");
     staffidTextField7.setText("");
   
    }//GEN-LAST:event_resetButton2ActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
          if((nameTextField1.getText().equals("")) ||(surnameTextField2.getText().equals(""))|| (sexTextField3.getText().equals(""))||(addTextField4.getText().equals(""))||
             (phonenoTextField5.getText().equals("")) || (BalanceTextField6.getText().equals(""))|| (staffidTextField7.getText().equals("")))
          {
           JOptionPane.showMessageDialog(this,"Please Fill All Fields");
          }
          
          else if(!BalanceTextField6.getText().matches("\\d+"))
            {
              JOptionPane.showMessageDialog(null,"Balance must be digits","Invalid",JOptionPane.INFORMATION_MESSAGE);    
            }
          else{
               try
                  {
                   Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                   con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;DatabaseName=AccountsDbs","sa","sa");
                   ps = con.prepareStatement("insert into CustomersAcct(vCusName,vCusSurname,vSex,vAddress,cPhoneNo,mBal,idNo) values(?,?,?,?,?,?,?)");
                
                String vCusName = nameTextField1.getText();
                String vCusSurname = surnameTextField2.getText();
                String VSex = sexTextField3.getText();
                String vAddress = addTextField4.getText();
                String cPhoneNo = phonenoTextField5.getText();
                String mBal = BalanceTextField6.getText();
                String idNo = staffidTextField7.getText();
                
                ps.setString(1, vCusName);
                ps.setString(2, vCusSurname);
                ps.setString(3, VSex);
                ps.setString(4, vAddress);
                ps.setString(5, cPhoneNo);
                ps.setString(6, mBal);
                ps.setString(7, idNo);
                
                rowsAffected = ps.executeUpdate();
                if(rowsAffected > 0)
                {
                    JOptionPane.showMessageDialog(null,"Record inserted successfully","Successful Entry",JOptionPane.INFORMATION_MESSAGE);
                    nameTextField1.setText("");
                    surnameTextField2.setText("");
                    sexTextField3.setText("");
                    addTextField4.setText("");
                    phonenoTextField5.setText("");
                    BalanceTextField6.setText("");
                    staffidTextField7.setText("");
                }
                
                //rs = stmt.executeQuery("Select * from AccountUsers where iAu = 001");
                //rs.next();
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex.toString(),"Failed to insert",JOptionPane.WARNING_MESSAGE);
            }
            finally{
                   try{
                        con.close();
                      }
                   catch(SQLException e){
                
                }
            }
        }            

          
    }//GEN-LAST:event_submitButton1ActionPerformed

    private void nameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextField1ActionPerformed

    private void surnameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameTextField2ActionPerformed

    private void sexTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexTextField3ActionPerformed

    private void addTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTextField4ActionPerformed

    private void phonenoTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoTextField5ActionPerformed

    private void BalanceTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceTextField6ActionPerformed

    private void staffidTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffidTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffidTextField7ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        LoginForm lf =new LoginForm();
        lf.setVisible(true);
        setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void accountNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNoTextFieldActionPerformed

    private void amountInWordsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountInWordsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountInWordsTextFieldActionPerformed

    private void withdrawalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawalTextFieldActionPerformed

    private void clearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton1ActionPerformed
         accountNoTextField.setText("");
         withdrawalTextField.setText("");
         amountInWordsTextField.setText("");
    }//GEN-LAST:event_clearButton1ActionPerformed

    private void depositAmtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositAmtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositAmtTextFieldActionPerformed

    private void accountNo2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNo2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNo2TextFieldActionPerformed

    private void amtInWordsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtInWordsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtInWordsTextFieldActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
         if((accountNo2TextField.getText().equals("")) ||(amtInWordsTextField.getText().equals(""))|| (depositAmtTextField.getText().equals("")))
             
          {
           JOptionPane.showMessageDialog(this,"Please Fill All Fields");
          }
          
          else if(!accountNo2TextField.getText().matches("\\d+"))
            {
              JOptionPane.showMessageDialog(null,"Deposit amount must be digits","Invalid",JOptionPane.INFORMATION_MESSAGE);    
            }
          
           else if(accountNo2TextField.getText().length()!=10)
            {
              JOptionPane.showMessageDialog(this,"Account number must be 10 digits","Invalid",JOptionPane.INFORMATION_MESSAGE);    
            }
          else{
               try
                  {
                   Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                   con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;DatabaseName=AccountsDbs","sa","sa");
                   ps = con.prepareStatement("insert into depositAccount(iAcNo,AmtDeposited,Amtinwords) values(?,?,?)");
                
                String iAcNo = accountNo2TextField.getText();
                String AmtDeposited  = depositAmtTextField.getText();
                String Amtinwords = amtInWordsTextField.getText();
               
                
                ps.setString(1, iAcNo);
                ps.setString(2, AmtDeposited);
                ps.setString(3, Amtinwords);
                
                rowsAffected = ps.executeUpdate();
                if(rowsAffected > 0)
                {
                    JOptionPane.showMessageDialog(null,"Record inserted successfully","Successful Entry",JOptionPane.INFORMATION_MESSAGE);
                    accountNo2TextField.setText("");
                    depositAmtTextField.setText("");
                    amtInWordsTextField.setText("");
                    
                }
                
                //rs = stmt.executeQuery("Select * from AccountUsers where iAu = 001");
                //rs.next();
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex.toString(),"Failed to insert",JOptionPane.WARNING_MESSAGE);
            }
            finally{
                   try{
                        con.close();
                      }
                   catch(SQLException e){
                
                }
            }
        }            

    }//GEN-LAST:event_depositButtonActionPerformed

    private void clearButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton3ActionPerformed
        accountNo2TextField.setText("");
        depositAmtTextField.setText("");
        amtInWordsTextField.setText("");
    }//GEN-LAST:event_clearButton3ActionPerformed

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed
       LoginForm lf =new LoginForm();
       lf.setVisible(true);
       setLocationRelativeTo(null);
       this.setVisible(false);
    }//GEN-LAST:event_backButton3ActionPerformed

    private void acctNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acctNoTextFieldActionPerformed
      
       
    }//GEN-LAST:event_acctNoTextFieldActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
         if(acctNoTextField.getText().equals(""))
       {
         JOptionPane.showMessageDialog(this,"Account Number must be in digits.");
       }
       
       else if(!acctNoTextField.getText().matches("\\d+"))
       {
        JOptionPane.showMessageDialog(this,"Account Number must be digits.");
       }
       
       else if(acctNoTextField.getText().length()!=10)
       {
        JOptionPane.showMessageDialog(this,"Account Number must be 10 digits.");
       }
       else
       {
          try{
               Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
               con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;DatabaseName=AccountsDbs","sa","sa");
               ps = con.prepareStatement("select * from CustomersAcct where iAcNo=?");
               ps.setInt(1, Integer.parseInt(acctNoTextField.getText()));
               
               rs=ps.executeQuery();
               rs.next();
               //accNoCha.setText(rs.getString(iAcNo));
               accNoCha.setText(Integer.toString(rs.getInt("iAcNo")));
               name.setText(rs.getString("vCusName"));
               surname.setText(rs.getString("vCusSurname"));
               balance.setText(String.format("N%,.2f", rs.getDouble("mBal")));
               //balance.setText(Double.toString(rs.getDouble("mBal")));      
                   
             }
          catch(Exception e)
            {
              JOptionPane.showMessageDialog(null, ex.toString(),"Failed",JOptionPane.ERROR_MESSAGE);
            }
            finally{
                   try{
                        con.close();
                      }
                   catch(Exception ex1)
                   {
                        JOptionPane.showMessageDialog(null, ex.toString(),"Failed",JOptionPane.ERROR_MESSAGE);
                   }
        }  
                  
      }    
    }//GEN-LAST:event_checkButtonActionPerformed

    private void clearButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton2ActionPerformed
       acctNoTextField.setText("");
       depositAmtTextField.setText("");
       amtInWordsTextField.setText("");
    }//GEN-LAST:event_clearButton2ActionPerformed
           
    private void withdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalButtonActionPerformed
        if((accountNoTextField.getText().equals("")) ||(amountInWordsTextField.getText().equals(""))|| (withdrawalTextField.getText().equals("")))
             
          {
           JOptionPane.showMessageDialog(this,"Please Fill All Fields");
          }
          
          else if(!accountNoTextField.getText().matches("\\d+"))
            {
              JOptionPane.showMessageDialog(null,"Withdrawal amount must be digits","Invalid",JOptionPane.INFORMATION_MESSAGE);    
            }
          
          else if(accountNoTextField.getText().length()!=10)
            {
              JOptionPane.showMessageDialog(this,"Account number must be 10 digits","Invalid",JOptionPane.INFORMATION_MESSAGE);    
            }
          else{
               try
                  {
                   Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                   con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;DatabaseName=AccountsDbs","sa","sa");
                   ps = con.prepareStatement("insert into withdAccount(iAcNo,Amtwithdrawn,Amtinwords) values(?,?,?)");
                
                String iAcNo = accountNoTextField.getText();
                String Amtwithdrawn  = withdrawalTextField.getText();
                String Amtinwords = amountInWordsTextField.getText();
               
                
                ps.setString(1, iAcNo);
                ps.setString(2, Amtwithdrawn);
                ps.setString(3, Amtinwords);
                
                rowsAffected = ps.executeUpdate();
                if(rowsAffected > 0)
                {
                    JOptionPane.showMessageDialog(null,"Record inserted successfully","Successful Entry",JOptionPane.INFORMATION_MESSAGE);
                    accountNoTextField.setText("");
                    withdrawalTextField.setText("");
                    amountInWordsTextField.setText("");
                    
                }
                
                //rs = stmt.executeQuery("Select * from AccountUsers where iAu = 001");
                //rs.next();
            }
            catch(Exception ex){
                 JOptionPane.showMessageDialog(null, ex.toString(),"Failed to insert",JOptionPane.WARNING_MESSAGE);
            }
            finally{
                   try{
                        con.close();
                      }
                   catch(SQLException e){
                
                }
            }
        }            

    }//GEN-LAST:event_withdrawalButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        LoginForm lf =new LoginForm();
        lf.setVisible(true);
        setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_backButton1ActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        LoginForm lf =new LoginForm();
        lf.setVisible(true);
        setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_backButton2ActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BalanceTextField6;
    private javax.swing.JLabel accNoCha;
    private javax.swing.JTextField accountNo2TextField;
    private javax.swing.JTextField accountNoTextField;
    private javax.swing.JTextField acctNoTextField;
    private javax.swing.JTextField addTextField4;
    private javax.swing.JTextField amountInWordsTextField;
    private javax.swing.JTextField amtInWordsTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButton3;
    private javax.swing.JLabel balance;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton clearButton1;
    private javax.swing.JButton clearButton2;
    private javax.swing.JButton clearButton3;
    private javax.swing.JTextField depositAmtTextField;
    private javax.swing.JButton depositButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JTextField phonenoTextField5;
    private javax.swing.JButton resetButton2;
    private javax.swing.JTextField sexTextField3;
    private javax.swing.JTextField staffidTextField7;
    private javax.swing.JButton submitButton1;
    private javax.swing.JLabel surname;
    private javax.swing.JTextField surnameTextField2;
    private javax.swing.JButton withdrawalButton;
    private javax.swing.JTextField withdrawalTextField;
    // End of variables declaration//GEN-END:variables


    

       
    
}
